SET SERVEROUTPUT ON;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF';
CREATE TABLE ROLURI (
IdRol NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NumeRol VARCHAR2(50) NOT NULL UNIQUE,
Descriere VARCHAR2(500),
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT chk_nume_rol CHECK (NumeRol IN ('CLIENT', 'BROKER', 'ADMIN'))
);
CREATE TABLE UTILIZATORI (
IdUtilizator NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nume VARCHAR2(100) NOT NULL,
Prenume VARCHAR2(100) NOT NULL,
Username VARCHAR2(50) NOT NULL UNIQUE,
Email VARCHAR2(255) NOT NULL UNIQUE,
Parola VARCHAR2(255) NOT NULL,
NumarTelefon VARCHAR2(20),
EmailVerified NUMBER(1) DEFAULT 0,
PhoneVerified NUMBER(1) DEFAULT 0,
DataNastere DATE NOT NULL,
IdRol NUMBER NOT NULL,
IsDeleted NUMBER(1) DEFAULT 0,
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
UpdatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT chk_email_verified CHECK (EmailVerified IN (0, 1)),
CONSTRAINT chk_phone_verified CHECK (PhoneVerified IN (0, 1)),
CONSTRAINT chk_is_deleted CHECK (IsDeleted IN (0, 1)),
CONSTRAINT fk_utilizatori_rol FOREIGN KEY (IdRol) REFERENCES ROLURI(IdRol),
CONSTRAINT chk_email_format CHECK (REGEXP_LIKE(Email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')),
CONSTRAINT chk_telefon_format CHECK (NumarTelefon IS NULL OR REGEXP_LIKE(NumarTelefon, '^[0-9]{10}$'))
);
CREATE TABLE BANCI (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Name VARCHAR2(200) NOT NULL UNIQUE,
CommissionPercent NUMBER(5,2) NOT NULL,
Active NUMBER(1) DEFAULT 1,
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT chk_commission CHECK (CommissionPercent BETWEEN 0 AND 100),
CONSTRAINT chk_bank_active CHECK (Active IN (0, 1))
);
CREATE TABLE APLICATII (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
UserId NUMBER NOT NULL,
Status VARCHAR2(50) DEFAULT 'INREGISTRAT' NOT NULL,
TypeCredit VARCHAR2(50),
TipOperatiune VARCHAR2(50),
SalariuNet NUMBER(18,2),
BonuriMasa NUMBER(1),
SumaBonuriMasa NUMBER(18,2),
VechimeLuni NUMBER,
NrCrediteBanci NUMBER,
ListaBanciActive CLOB,
NrIfn NUMBER,
Poprire NUMBER(1),
SoldTotal NUMBER(18,2),
Intarzieri NUMBER(1),
IntarzieriNumar NUMBER,
CardCredit CLOB,
Overdraft CLOB,
Codebitori CLOB,
Scoring NUMBER(5,2),
Dti NUMBER(5,2),
RecommendedLevel VARCHAR2(50),
SumaAprobata NUMBER(18,2),
Comision NUMBER(18,2),
DataDisbursare TIMESTAMP,
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
UpdatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT fk_aplicatii_user FOREIGN KEY (UserId) REFERENCES UTILIZATORI(IdUtilizator),
CONSTRAINT chk_status CHECK (Status IN ('INREGISTRAT', 'IN_PROCESARE', 'APROBAT', 'REFUZAT', 'ANULAT')),
CONSTRAINT chk_type_credit CHECK (TypeCredit IS NULL OR TypeCredit IN ('IPOTECAR', 'NEVOI_PERSONALE', 'REFINANTARE')),
CONSTRAINT chk_tip_operatiune CHECK (TipOperatiune IS NULL OR TipOperatiune IN ('NOU', 'REFINANTARE')),
CONSTRAINT chk_scoring CHECK (Scoring IS NULL OR Scoring BETWEEN 300 AND 850),
CONSTRAINT chk_dti CHECK (Dti IS NULL OR Dti BETWEEN 0 AND 100),
CONSTRAINT chk_salariu CHECK (SalariuNet IS NULL OR SalariuNet >= 0),
CONSTRAINT chk_bonuri_masa CHECK (BonuriMasa IS NULL OR BonuriMasa IN (0, 1)),
CONSTRAINT chk_poprire CHECK (Poprire IS NULL OR Poprire IN (0, 1)),
CONSTRAINT chk_intarzieri CHECK (Intarzieri IS NULL OR Intarzieri IN (0, 1))
);
CREATE TABLE APPLICATION_BANKS (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ApplicationId NUMBER NOT NULL,
BankId NUMBER NOT NULL,
Status VARCHAR2(50) DEFAULT 'PENDING',
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT fk_app_banks_app FOREIGN KEY (ApplicationId) REFERENCES APLICATII(Id) ON DELETE CASCADE,
CONSTRAINT fk_app_banks_bank FOREIGN KEY (BankId) REFERENCES BANCI(Id),
CONSTRAINT uk_app_bank UNIQUE (ApplicationId, BankId),
CONSTRAINT chk_app_bank_status CHECK (Status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);
CREATE TABLE DOCUMENTE (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ApplicationId NUMBER NOT NULL,
TipDocument VARCHAR2(50) NOT NULL,
NumeFisier VARCHAR2(255) NOT NULL,
Path VARCHAR2(1000) NOT NULL,
SizeBytes NUMBER NOT NULL,
MimeType VARCHAR2(100),
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT fk_documente_app FOREIGN KEY (ApplicationId) REFERENCES APLICATII(Id) ON DELETE CASCADE,
CONSTRAINT chk_tip_document CHECK (TipDocument IN ('CI', 'FLUTURAS', 'EXTRAS_CONT', 'CONTRACT', 'ALTUL')),
CONSTRAINT chk_size_bytes CHECK (SizeBytes > 0)
);
CREATE TABLE AGREEMENTS (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ApplicationId NUMBER NOT NULL,
TipAcord VARCHAR2(50) NOT NULL,
Status VARCHAR2(50) DEFAULT 'ACTIV',
DataAcord TIMESTAMP DEFAULT SYSTIMESTAMP,
DataExpirare TIMESTAMP,
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT fk_agreements_app FOREIGN KEY (ApplicationId) REFERENCES APLICATII(Id) ON DELETE CASCADE,
CONSTRAINT chk_tip_acord CHECK (TipAcord IN ('TERMENI_CONDITII', 'CONSENT_GDPR', 'MANDAT_BROKER')),
CONSTRAINT chk_agreement_status CHECK (Status IN ('ACTIV', 'EXPIRAT', 'REVOCAT')),
CONSTRAINT chk_data_expirare CHECK (DataExpirare IS NULL OR DataExpirare > DataAcord)
);
CREATE TABLE LEADURI (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
Nume VARCHAR2(100) NOT NULL,
Prenume VARCHAR2(100) NOT NULL,
Email VARCHAR2(255),
NumarTelefon VARCHAR2(20),
Status VARCHAR2(50) DEFAULT 'NOU',
Source VARCHAR2(100),
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT chk_lead_status CHECK (Status IN ('NOU', 'CONTACTAT', 'CONVERTIT', 'RESPINS')),
CONSTRAINT chk_lead_email CHECK (Email IS NULL OR REGEXP_LIKE(Email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')),
CONSTRAINT chk_lead_telefon CHECK (NumarTelefon IS NULL OR REGEXP_LIKE(NumarTelefon, '^[0-9]{10}$'))
);
CREATE TABLE CONSENTURI (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
UserId NUMBER NOT NULL,
TipConsent VARCHAR2(50) NOT NULL,
Status VARCHAR2(50) DEFAULT 'ACTIV',
DataConsent TIMESTAMP DEFAULT SYSTIMESTAMP,
DataExpirare TIMESTAMP,
IpAddress VARCHAR2(45),
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT fk_consenturi_user FOREIGN KEY (UserId) REFERENCES UTILIZATORI(IdUtilizator) ON DELETE CASCADE,
CONSTRAINT chk_tip_consent CHECK (TipConsent IN ('PROCESARE_DATE', 'MARKETING', 'COMUNICARE_BANCI')),
CONSTRAINT chk_consent_status CHECK (Status IN ('ACTIV', 'EXPIRAT', 'REVOCAT'))
);
CREATE TABLE MANDATE (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
UserId NUMBER NOT NULL,
BrokerId NUMBER NOT NULL,
Status VARCHAR2(50) DEFAULT 'ACTIV',
DataMandat TIMESTAMP DEFAULT SYSTIMESTAMP,
DataExpirare TIMESTAMP,
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT fk_mandate_user FOREIGN KEY (UserId) REFERENCES UTILIZATORI(IdUtilizator) ON DELETE CASCADE,
CONSTRAINT fk_mandate_broker FOREIGN KEY (BrokerId) REFERENCES UTILIZATORI(IdUtilizator),
CONSTRAINT chk_mandate_status CHECK (Status IN ('ACTIV', 'EXPIRAT', 'REVOCAT')),
CONSTRAINT chk_mandate_expirare CHECK (DataExpirare IS NULL OR DataExpirare > DataMandat)
);
CREATE TABLE USER_FINANCIAL_DATA (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
UserId NUMBER NOT NULL UNIQUE,
SalariuNet NUMBER(18,2),
BonuriMasa NUMBER(1),
SumaBonuriMasa NUMBER(18,2),
VenitTotal NUMBER(18,2),
SoldTotal NUMBER(18,2),
RataTotalaLunara NUMBER(18,2),
NrCrediteBanci NUMBER,
NrIfn NUMBER,
Poprire NUMBER(1),
Intarzieri NUMBER(1),
IntarzieriNumar NUMBER,
Dti NUMBER(5,2),
ScoringLevel VARCHAR2(50),
RecommendedLevel VARCHAR2(50),
LastUpdated TIMESTAMP DEFAULT SYSTIMESTAMP,
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT fk_financial_data_user FOREIGN KEY (UserId) REFERENCES UTILIZATORI(IdUtilizator) ON DELETE CASCADE,
CONSTRAINT chk_financial_salariu CHECK (SalariuNet IS NULL OR SalariuNet >= 0),
CONSTRAINT chk_financial_dti CHECK (Dti IS NULL OR Dti BETWEEN 0 AND 100),
CONSTRAINT chk_financial_scoring CHECK (ScoringLevel IS NULL OR ScoringLevel IN ('FOARTE_BUNA', 'BUNA', 'MEDIE', 'SLABA', 'FOARTE_SLABA')),
CONSTRAINT chk_financial_bonuri CHECK (BonuriMasa IS NULL OR BonuriMasa IN (0, 1)),
CONSTRAINT chk_financial_poprire CHECK (Poprire IS NULL OR Poprire IN (0, 1)),
CONSTRAINT chk_financial_intarzieri CHECK (Intarzieri IS NULL OR Intarzieri IN (0, 1))
);
CREATE TABLE USER_SESSIONS (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
UserId NUMBER NOT NULL,
Token VARCHAR2(500) NOT NULL UNIQUE,
ExpiresAt TIMESTAMP NOT NULL,
IpAddress VARCHAR2(45),
UserAgent VARCHAR2(500),
CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT fk_session_user FOREIGN KEY (UserId) REFERENCES UTILIZATORI(IdUtilizator) ON DELETE CASCADE,
CONSTRAINT chk_session_expires CHECK (ExpiresAt > CreatedAt)
);
CREATE TABLE AUDIT_LOG (
Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TableName VARCHAR2(100) NOT NULL,
Operation VARCHAR2(10) NOT NULL,
UserId NUMBER,
OldValues CLOB,
NewValues CLOB,
IpAddress VARCHAR2(45),
Timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
CONSTRAINT chk_audit_operation CHECK (Operation IN ('INSERT', 'UPDATE', 'DELETE'))
);
CREATE TABLE MESAJE (
cod_mesaj NUMBER PRIMARY KEY,
mesaj VARCHAR2(255) NOT NULL,
tip_mesaj VARCHAR2(1) NOT NULL,
creat_de VARCHAR2(40) NOT NULL,
creat_la DATE NOT NULL,
CONSTRAINT chk_tip_mesaj CHECK (tip_mesaj IN ('E', 'W', 'I'))
);
CREATE SEQUENCE seq_mesaje
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
CREATE INDEX idx_applications_userid ON APLICATII(UserId);
CREATE INDEX idx_applications_status ON APLICATII(Status);
CREATE INDEX idx_applications_created ON APLICATII(CreatedAt);
CREATE INDEX idx_documents_applicationid ON DOCUMENTE(ApplicationId);
CREATE INDEX idx_consenturi_userid ON CONSENTURI(UserId);
CREATE INDEX idx_consenturi_status ON CONSENTURI(Status);
CREATE INDEX idx_mandate_userid ON MANDATE(UserId);
CREATE INDEX idx_mandate_brokerid ON MANDATE(BrokerId);
CREATE INDEX idx_mandate_status ON MANDATE(Status);
CREATE INDEX idx_audit_log_timestamp ON AUDIT_LOG(Timestamp);
CREATE INDEX idx_audit_log_tablename ON AUDIT_LOG(TableName);
CREATE INDEX idx_session_userid ON USER_SESSIONS(UserId);
CREATE INDEX idx_session_expires ON USER_SESSIONS(ExpiresAt);
CREATE INDEX idx_utilizatori_idrol ON UTILIZATORI(IdRol);
INSERT INTO ROLURI (NumeRol, Descriere) VALUES ('CLIENT', 'Utilizator standard care aplică pentru credite');
INSERT INTO ROLURI (NumeRol, Descriere) VALUES ('BROKER', 'Broker autorizat care procesează cererile de credit');
INSERT INTO ROLURI (NumeRol, Descriere) VALUES ('ADMIN', 'Administrator cu acces complet la sistem');
COMMIT;
CREATE OR REPLACE TRIGGER trg_utilizatori_varsta
BEFORE INSERT OR UPDATE OF DataNastere ON UTILIZATORI
FOR EACH ROW
BEGIN
IF :NEW.DataNastere > ADD_MONTHS(SYSDATE, -216) THEN
RAISE_APPLICATION_ERROR(-20005, 'Utilizatorul trebuie să aibă minim 18 ani');
END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_utilizatori_updated
BEFORE UPDATE ON UTILIZATORI
FOR EACH ROW
BEGIN
:NEW.UpdatedAt := SYSTIMESTAMP;
END;
/
CREATE OR REPLACE TRIGGER trg_aplicatii_updated
BEFORE UPDATE ON APLICATII
FOR EACH ROW
BEGIN
:NEW.UpdatedAt := SYSTIMESTAMP;
END;
/
SELECT table_name, num_rows
FROM user_tables
WHERE table_name IN ('ROLURI', 'UTILIZATORI', 'APLICATII', 'BANCI', 'DOCUMENTE', 'CONSENTURI', 'MANDATE', 'MESAJE')
ORDER BY table_name;
BEGIN
DBMS_OUTPUT.PUT_LINE('========================================');
DBMS_OUTPUT.PUT_LINE('Tabelele au fost create cu succes!');
DBMS_OUTPUT.PUT_LINE('========================================');
END;
/