// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyShop.DataAccess.EntityFramework;

#nullable disable

namespace MoneyShop.DataAccess.Migrations
{
    [DbContext(typeof(MoneyShopContext))]
    partial class MoneyShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyShop.Entities.Entities.Agreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgreementType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PdfBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SignatureImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Version")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("1.0");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Agreements", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BonuriMasa")
                        .HasColumnType("bit");

                    b.Property<string>("CardCredit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codebitori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataDisbursare")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Dti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Intarzieri")
                        .HasColumnType("bit");

                    b.Property<int?>("IntarzieriNumar")
                        .HasColumnType("int");

                    b.Property<string>("ListaBanciActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NrCrediteBanci")
                        .HasColumnType("int");

                    b.Property<int?>("NrIfn")
                        .HasColumnType("int");

                    b.Property<string>("Overdraft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Poprire")
                        .HasColumnType("bit");

                    b.Property<string>("RecommendedLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SalariuNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Scoring")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoldTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("INREGISTRAT");

                    b.Property<decimal?>("SumaAprobata")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SumaBonuriMasa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipOperatiune")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeCredit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VechimeLuni")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.ApplicationBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("BankId");

                    b.ToTable("ApplicationBanks", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.BacDocument", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocument"));

                    b.Property<byte[]>("Continut")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("DataAdaugare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NumeDocument")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipMaterie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDocument")
                        .HasName("PK__BacDocum__BEAAD0BAD56E4F0E");

                    b.ToTable("BacDocuments");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Banks", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.BrokerDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExcelFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("BrokerDirectories", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Consent", b =>
                {
                    b.Property<Guid>("ConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsentTextSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("DeviceHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("DocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("granted");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ConsentId");

                    b.HasIndex("DocId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId", "ConsentType", "GrantedAt");

                    b.ToTable("Consents", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("AzureBlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("MandateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("MandateId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Favorites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.KycFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileContentBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("KycId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Sha256Hash")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("FileId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("KycId");

                    b.ToTable("KycFiles", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.KycSession", b =>
                {
                    b.Property<Guid>("KycId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cnp")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KycType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilizatoriIdUtilizator")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("KycId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UtilizatoriIdUtilizator");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("KycSessions", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Converted")
                        .HasColumnType("bit");

                    b.Property<int?>("ConvertedToApplicationId")
                        .HasColumnType("int");

                    b.Property<int?>("ConvertedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("GdprConsent")
                        .HasColumnType("bit");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Judet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TypeCredit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.LegalDoc", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DocId");

                    b.HasIndex("DocType", "IsActive");

                    b.HasIndex("DocType", "Version")
                        .IsUnique();

                    b.ToTable("LegalDocs", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Mandate", b =>
                {
                    b.Property<Guid>("MandateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsentEventId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MandateType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("credit_eligibility_only");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MandateId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId", "Status", "GrantedAt");

                    b.ToTable("Mandates", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DeviceHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("OtpHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilizatoriIdUtilizator")
                        .HasColumnType("int");

                    b.HasKey("OtpId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UtilizatoriIdUtilizator");

                    b.HasIndex("Phone", "Purpose", "CreatedAt");

                    b.ToTable("OtpChallenges", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Proiecte", b =>
                {
                    b.Property<int>("IdProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProject"));

                    b.Property<string>("ContestCreator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContestRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("FileFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProjectFile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilizatoriIdUtilizator")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProject")
                        .HasName("PK__Proiecte__187B9AAFDE323DC0");

                    b.HasIndex("UtilizatoriIdUtilizator");

                    b.ToTable("Proiecte", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Roluri", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NumeRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roluri__2A49584C65FE7A4A");

                    b.ToTable("Roluri", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.SavedProject", b =>
                {
                    b.Property<int>("IdSavedProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSavedProject"));

                    b.Property<DateTime?>("DataSalvare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdProiect")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilizator")
                        .HasColumnType("int");

                    b.HasKey("IdSavedProject")
                        .HasName("PK__SavedPro__E5878A3ADC55E572");

                    b.HasIndex("IdProiect");

                    b.HasIndex("IdUtilizator");

                    b.ToTable("SavedProjects");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("DeviceHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilizatoriIdUtilizator")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UtilizatoriIdUtilizator");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.SubjectMap", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<byte[]>("CnpHash")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.Property<string>("CnpLast4")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("CnpHash")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SubjectMaps", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.UserFinancialData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BonuriMasa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Dti")
                        .HasColumnType("decimal(5,4)");

                    b.Property<bool?>("Intarzieri")
                        .HasColumnType("bit");

                    b.Property<int?>("IntarzieriNumar")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NrCrediteBanci")
                        .HasColumnType("int");

                    b.Property<int?>("NrIfn")
                        .HasColumnType("int");

                    b.Property<bool?>("Poprire")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RataTotalaLunara")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecommendedLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SalariuNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScoringLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SoldTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SumaBonuriMasa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VenitTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdated");

                    b.HasIndex("UserId");

                    b.ToTable("UserFinancialData", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Utilizatori", b =>
                {
                    b.Property<int>("IdUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilizator"));

                    b.Property<DateTime?>("DataIncepere")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataNastere")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Mail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumarTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Parola")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdUtilizator")
                        .HasName("PK__Utilizat__99101D6D31235E34");

                    b.HasIndex(new[] { "Username" }, "UQ__Utilizat__536C85E4B4BA6916")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Utilizatori", (string)null);
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Agreement", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Application", "Application")
                        .WithMany("Agreements")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Application", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.ApplicationBank", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Application", "Application")
                        .WithMany("ApplicationBanks")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyShop.Entities.Entities.Bank", "Bank")
                        .WithMany("ApplicationBanks")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.BrokerDirectory", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Consent", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.LegalDoc", "Doc")
                        .WithMany("Consents")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyShop.Entities.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doc");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Document", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyShop.Entities.Entities.Mandate", null)
                        .WithMany("Documents")
                        .HasForeignKey("MandateId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Favorites", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Proiecte", "Project")
                        .WithMany("Favorites")
                        .HasForeignKey("ProjectId")
                        .IsRequired();

                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.KycFile", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.KycSession", "KycSession")
                        .WithMany("KycFiles")
                        .HasForeignKey("KycId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KycSession");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.KycSession", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", null)
                        .WithMany("KycSessions")
                        .HasForeignKey("UtilizatoriIdUtilizator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Mandate", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.OtpChallenge", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", null)
                        .WithMany("OtpChallenges")
                        .HasForeignKey("UtilizatoriIdUtilizator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Proiecte", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", null)
                        .WithMany("Proiectes")
                        .HasForeignKey("UtilizatoriIdUtilizator");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.SavedProject", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Proiecte", "IdProiectNavigation")
                        .WithMany("SavedProjects")
                        .HasForeignKey("IdProiect")
                        .IsRequired()
                        .HasConstraintName("FK__SavedProj__IdPro__46E78A0C");

                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "IdUtilizatorNavigation")
                        .WithMany("SavedProjects")
                        .HasForeignKey("IdUtilizator")
                        .IsRequired()
                        .HasConstraintName("FK__SavedProj__IdUti__45F365D3");

                    b.Navigation("IdProiectNavigation");

                    b.Navigation("IdUtilizatorNavigation");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Session", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UtilizatoriIdUtilizator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.SubjectMap", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.UserFinancialData", b =>
                {
                    b.HasOne("MoneyShop.Entities.Entities.Utilizatori", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Application", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("ApplicationBanks");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Bank", b =>
                {
                    b.Navigation("ApplicationBanks");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.KycSession", b =>
                {
                    b.Navigation("KycFiles");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.LegalDoc", b =>
                {
                    b.Navigation("Consents");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Mandate", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Proiecte", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("SavedProjects");
                });

            modelBuilder.Entity("MoneyShop.Entities.Entities.Utilizatori", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("KycSessions");

                    b.Navigation("OtpChallenges");

                    b.Navigation("Proiectes");

                    b.Navigation("SavedProjects");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
