-- =====================================================
-- VERIFICARE VIEW-URI ETL EXTRACT
-- =====================================================

-- Verifică view-urile create
SELECT VIEW_NAME, STATUS 
FROM USER_VIEWS 
WHERE VIEW_NAME LIKE 'VW_ETL_EXTRACT%'
ORDER BY VIEW_NAME;

-- Testează fiecare view
SELECT 'VW_ETL_EXTRACT_APLICATII' as view_name, COUNT(*) as count FROM VW_ETL_EXTRACT_APLICATII
UNION ALL
SELECT 'VW_ETL_EXTRACT_UTILIZATORI', COUNT(*) FROM VW_ETL_EXTRACT_UTILIZATORI
UNION ALL
SELECT 'VW_ETL_EXTRACT_BANCI', COUNT(*) FROM VW_ETL_EXTRACT_BANCI
UNION ALL
SELECT 'VW_ETL_EXTRACT_BROKERI', COUNT(*) FROM VW_ETL_EXTRACT_BROKERI;

